In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
clients = pd.read_csv('clients.csv')
products = pd.read_csv('products.csv')

In [3]:
clients['first_redeem_date'].fillna(clients['first_issue_date'], inplace = True)
clients['first_issue_date1'] = clients['first_issue_date'].apply(lambda x: pd.to_datetime(x[:10]))
clients['first_redeem_date1'] = clients['first_redeem_date'].apply(lambda x: pd.to_datetime(x[:10]))
clients['dif_date'] = clients[['first_redeem_date','first_issue_date']].apply(lambda x: int(str(pd.to_datetime(x[0]) - pd.to_datetime(x[1])).split(' ')[0]), axis = 1)
clients['dif_date'] = clients['dif_date'].apply(lambda x: x if x != -1 else 0)

In [7]:
clients['day'] =  clients['first_redeem_date'].apply(lambda x : int(pd.to_datetime(x).day))

In [9]:
clients['month'] = clients['first_redeem_date'].apply(lambda x: int(pd.to_datetime(x).month))

In [11]:
clients = clients.drop(labels = ['first_issue_date', 'first_redeem_date', 'first_redeem_date1', 'first_issue_date1'], axis = 1)

In [15]:
clients['gender'] = le.fit_transform(clients['gender'])

In [ ]:
clients['age'] = clients['age'].apply(lambda x: '45' if (x > 80) | (x < 15) else x)

In [ ]:
products = products.drop(labels = ['level_1', 'level_2', 'level_3', 'level_4'], axis = 1)

In [4]:
clients

,client_id,first_issue_date,first_redeem_date,age,gender,first_issue_date1,first_redeem_date1,dif_date
0,000012768d,2017-08-05 15:40:48,2018-01-04 19:30:07,45,U,2017-08-05,2018-01-04,152
1,000036f903,2017-04-10 13:54:23,2017-04-23 12:37:56,72,F,2017-04-10,2017-04-23,12
2,000048b7a6,2018-12-15 13:33:11,2018-12-15 13:33:11,68,F,2018-12-15,2018-12-15,0
3,000073194a,2017-05-23 12:56:14,2017-11-24 11:18:01,60,F,2017-05-23,2017-11-24,184
4,00007c7133,2017-05-22 16:17:08,2018-12-31 17:17:33,67,U,2017-05-22,2018-12-31,588

In [14]:
purchases = pd.read_csv('purchases.csv')

In [10]:
train = pd.read_csv('uplift_train.csv')

In [11]:
train['target_new'] = train['treatment_flg']*train['target']

In [24]:
purchases['trn_sum_from_red'].fillna(0, inplace = True)

In [22]:
train = train.drop(labels = ['treatment_flg', 'target'], axis = 1)

In [13]:
le = LabelEncoder()

In [41]:
purchases['store_id'] = le.fit_transform(purchases['store_id'])

In [45]:
purchases['regular_points_received'] = purchases['regular_points_received'].astype(int)

In [47]:
purchases['express_points_received'] = purchases['express_points_received'].astype(int)
purchases['regular_points_spent'] = purchases['regular_points_spent'].astype(int)
purchases['express_points_spent'] = purchases['express_points_spent'].astype(int)
purchases['purchase_sum'] = purchases['purchase_sum'].astype(int)

In [49]:
purchases['product_quantity'] = purchases['product_quantity'].astype(int)
purchases['trn_sum_from_iss'] = purchases['trn_sum_from_iss'].astype(int)
purchases['trn_sum_from_red'] = purchases['trn_sum_from_red'].astype(int)

In [50]:
purchases.to_csv('purchases2.csv')

In [53]:
purchases.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45786568 entries, 0 to 45786567
Data columns (total 13 columns):
client_id                  object
transaction_id             object
transaction_datetime       object
regular_points_received    int32
express_points_received    int32
regular_points_spent       int32
express_points_spent       int32
purchase_sum               int32
store_id                   int32
product_id                 object
product_quantity           int32
trn_sum_from_iss           int32
trn_sum_from_red           int32
dtypes: int32(9), object(4)
memory usage: 13.3 GB

In [55]:
mer = pd.merge(train, purchases, on = 'client_id')

In [59]:
#products['segment_id'] = products['segment_id'].astype(int)

In [63]:
products[products['segment_id'].isna()]

,product_id,level_1,level_2,level_3,level_4,segment_id,brand_id,vendor_id,netto,is_own_trademark,is_alcohol
59,0058bda372,c3d3a8e8c6,de6f3b925a,68b1fb172a,741983ea3d,NaN,NaN,91ed29803e,0.250,0,0
69,00678eb1df,ec62ce61e3,a49a930a49,d1dc20357f,e83e5f0a95,NaN,NaN,01f7c589b1,0.038,0,0
121,00c8c8e837,c3d3a8e8c6,de6f3b925a,68b1fb172a,741983ea3d,NaN,8281de6bcb,6bc8b3c476,0.200,0,0
133,00de7e4339,ec62ce61e3,6b4ae3f25d,83f17acdfd,45e2127ec0,NaN,585124a4e4,6afe337e49,0.111,0,0
163,0116989c2c,c3d3a8e8c6,428e08386e,4797d587da,d39dc1f4bd,NaN,NaN,52a0b79928,0.100,0,0
180,0137cfc40f,ec62ce61e3,a49a930a49,d1dc20357f,e83e5f0a95,NaN,0d6f137fb6,01f7c589b1,0.027,0,0
184,013abbad2d,c3d3a8e8c6,de6f3b925a,68b1fb172a,741983ea3d,NaN,f6daae555c,e3dd425ae9,0.200,0,0
226,018bf0a14e,e344ab2e71,52f13dac0c,d3cfe81323,aa388bf81c,NaN,0d6f137fb6,9e44df7585,0.650,0,0
228,018ff5e95f,ec62ce61e3,a49a930a49,d1dc20357f,bcf194d894,NaN,NaN,ef3b92f068,0.027,0,0
255,01b0d48367,ec62ce61e3,a49a930a49,d1dc20357f,4062922114,NaN,bf6b01243c,05382f3dad,0.040,0,0
293,01db945fa6,ec62ce61e3,a49a930a49,d1dc20357f,f8b3e04a1d,NaN,c17d9698ab,7a244f81d3,0.055,0,0
300,01e6c564b4,ec62ce61e3,6b4ae3f25d,83f17acdfd,45e2127ec0,NaN,NaN,83f98e6dc3,0.038,0,0
318,0209190fc7,ec62ce61e3,6b4ae3f25d,a5b820d60d,390cb52cd1,NaN,NaN,8ad28e1ef9,0.048,0,0
319,020b6fd175,c3d3a8e8c6,de6f3b925a,68b1fb172a,9b5cb21dca,NaN,f5d04331d6,ad5533febf,0.300,0,0
342,0224b2ea6c,e344ab2e71,52f13dac0c,38816369ce,27563baed9,NaN,NaN,ea4c5b2b16,0.350,0,0
425,02b274a54f,ec62ce61e3,a2963967ff,23177827cb,e495f9ca7d,NaN,NaN,dae27a2e3e,0.215,0,0
559,037638e4d8,ec62ce61e3,6b4ae3f25d,a07cfba194,bf34de1b0d,NaN,585124a4e4,6afe337e49,0.286,0,0
563,0377911c1d,ec62ce61e3,a49a930a49,d1dc20357f,4062922114,NaN,fb9464bfe4,05382f3dad,0.040,0,0
595,03ae8b809e,e344ab2e71,ed2ad1797c,dc4a4438c8,dea9c144c6,NaN,fce7934ead,95ea122ece,0.200,0,0
596,03b1ba5014,e344ab2e71,52f13dac0c,38816369ce,27563baed9,NaN,01c29d894c,f0d6a4ba61,0.350,0,0
606,03beb633be,c3d3a8e8c6,de6f3b925a,68b1fb172a,9b5cb21dca,NaN,0ba1425ed4,2d1446f0e6,0.150,0,0
654,0420fc09a1,ec62ce61e3,6b4ae3f25d,83f17acdfd,a18dab2f5e,NaN,585124a4e4,6afe337e49,0.097,0,0
693,044b18825e,ec62ce61e3,a49a930a49,d1dc20357f,83257ff23c,NaN,21c28deed8,9c17292571,0.030,0,0
711,0467c6e9d6,ec62ce61e3,6b4ae3f25d,87006cb40e,b4f37e7a4b,NaN,585124a4e4,6afe337e49,0.010,0,0
754,049ee456d0,c3d3a8e8c6,ad2b2e17d2,ca69ed9de2,43d353d87a,NaN,2d5dc2fc04,a5ed9be962,0.180,0,0
784,04cb83d55a,e344ab2e71,52f13dac0c,38816369ce,27563baed9,NaN,4992ae94c0,c79930e9ee,0.500,0,0
796,04d86b4b50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
842,052869db55,ec62ce61e3,6b4ae3f25d,a07cfba194,5220930373,NaN,36db06ee82,68b42db0f8,0.065,0,0
846,052f843273,e344ab2e71,52f13dac0c,38816369ce,27563baed9,NaN,4da2dc345f,10486c3cf0,0.200,0,0
883,05632e043f,e344ab2e71,52f13dac0c,38816369ce,27563baed9,NaN,NaN,fd06cbd672,0.350,0,0
...,...,...,...,...,...,...,...,...,...,...,...
42187,fadbbc07c7,e344ab2e71,52f13dac0c,38816369ce,27563baed9,NaN,b06ace74de,4a0962b676,0.500,0,0
42300,fb900c5b5a,ec62ce61e3,a49a930a49,d1dc20357f,4062922114,NaN,NaN,1e86392b01,0.100,0,0
42359,fbf501541f,c3d3a8e8c6,70ac384d6a,89f5389cc7,b40e19dd50,NaN,NaN,742e696cbb,0.300,0,0
42360,fbfb514158,ec62ce61e3,6b4ae3f25d,83f17acdfd,98d9029a38,NaN,NaN,3c835cf7b8,0.010,0,0
42373,fc13f57e5c,e344ab2e71,52f13dac0c,38816369ce,27563baed9,NaN,062b412aa8,0d9078583b,0.500,0,0
42413,fc55d109c8,e344ab2e71,52f13dac0c,d3cfe81323,aa388bf81c,NaN,0d6f137fb6,e62f91a5e0,0.600,0,0
42437,fc7cdfcac1,ec62ce61e3,a49a930a49,d1dc20357f,f8b3e04a1d,NaN,68f1daeced,1560f629a4,0.130,0,0
42451,fc89ef0c16,ec62ce61e3,a49a930a49,d1dc20357f,4062922114,NaN,5501d7043a,bfbdd07e85,0.040,0,0
42455,fc8d65fc22,ec62ce61e3,6b4ae3f25d,83f17acdfd,dce35470e4,NaN,cf1f6b46f8,e902a8ac20,0.065,0,0
42478,fca8690913,ec62ce61e3,a49a930a49,d1dc20357f,4062922114,NaN,5d94e463eb,662430e020,0.050,0,0
42506,fcd3cacce3,e344ab2e71,52f13dac0c,38816369ce,27563baed9,NaN,0d6f137fb6,5bdda7400e,0.350,0,0
42537,fd09bacdf2,e344ab2e71,52f13dac0c,d3cfe81323,aa388bf81c,NaN,5bbedaf707,7d5c04d1f4,0.680,0,0
42555,fd21048c98,c3d3a8e8c6,428e08386e,4797d587da,93f9ec2b60,NaN,NaN,52a0b79928,0.075,0,0
42601,fd5e489777,ec62ce61e3,a49a930a49,983ea82c4c,927c0ff07f,NaN,NaN,6d2e042f7e,0.055,0,0
42615,fd77232a43,ec62ce61e3,a49a930a49,d1dc20357f,e83e5f0a95,NaN,0d6f137fb6,01f7c589b1,0.034,0,0
42642,fd9325f001,c3d3a8e8c6,428e08386e,4797d587da,d39dc1f4bd,NaN,NaN,52a0b79928,0.075,0,0
42648,fd9b06114b,c3d3a8e8c6,428e08386e,4797d587da,d39dc1f4bd,NaN,NaN,52a0b79928,0.270,0,0
42649,fd9d8d30a0,ec62ce61e3,a49a930a49,d1dc20357f,e83e5f0a95,NaN,0608bd1f40,ef3b92f068,0.029,0,0
42685,fdd0d3b588,ec62ce61e3,6b4ae3f25d,83f17acdfd,98d9029a38,NaN,dc959e629b,a4017ca3f7,0.110,0,0
42716,fe03422dee,c3d3a8e8c6,de6f3b925a,68b1fb172a,9b5cb21dca,NaN,0c6b9a47cb,3c95c69958,0.300,0,0
42723,fe0ffae892,c3d3a8e8c6,de6f3b925a,68b1fb172a,350b4db7bd,NaN,0b334f7571,08dbce4deb,0.300,0,0
42727,fe1866fe4a,c3d3a8e8c6,ad2b2e17d2,ca69ed9de2,43d353d87a,NaN,062b7e85cd,4f276b13c1,0.170,0,0
42758,fe499bcc79,c3d3a8e8c6,428e08386e,4797d587da,d39dc1f4bd,NaN,4da2dc345f,a2a30fbd43,0.070,0,0
42839,febaebd1b4,ec62ce61e3,6b4ae3f25d,83f17acdfd,45e2127ec0,NaN,b06ace74de,ce9f483fa2,0.230,0,0
42917,ff314987dd,ec62ce61e3,6b4ae3f25d,83f17acdfd,45e2127ec0,NaN,b06ace74de,e14a8bae96,0.180,0,0
42934,ff4c77d9d5,ec62ce61e3,6b4ae3f25d,83f17acdfd,0310d7e231,NaN,0d6f137fb6,01ea898857,0.192,0,0
42959,ff79a66f06,ec62ce61e3,6b4ae3f25d,a5b820d60d,82d29ef746,NaN,0d6f137fb6,afbf4c8d34,0.100,0,0
42975,ff9b10bb99,c3d3a8e8c6,91fb12a54a,f67fc26a36,a39c4edd69,NaN,4da2dc345f,25d82db007,1.000,0,0
43006,ffcb44ca47,e344ab2e71,52f13dac0c,38816369ce,27563baed9,NaN,2eecd3f5bf,61a6172002,0.300,0,0
43018,ffe30fd6b7,c3d3a8e8c6,de6f3b925a,68b1fb172a,9b5cb21dca,NaN,NaN,f9bbe26657,0.200,0,0

In [66]:
products[(products['vendor_id']=='91ed29803e') & (products['netto']==0.250)]

,product_id,level_1,level_2,level_3,level_4,segment_id,brand_id,vendor_id,netto,is_own_trademark,is_alcohol
59,0058bda372,c3d3a8e8c6,de6f3b925a,68b1fb172a,741983ea3d,NaN,NaN,91ed29803e,0.25,0,0
21444,7fdb93862d,c3d3a8e8c6,de6f3b925a,68b1fb172a,9b5cb21dca,NaN,NaN,91ed29803e,0.25,0,0

In [77]:
inp = input()
inp += ' '
temp = []
out = ''
for x in range(len(inp)):
    if inp[x] == ' ':
        break
    else:
        if inp[x]==inp[x+1]:
            temp.append(inp[x])
        else:
            out +=inp[x]+str(len(temp)+1)
            temp = []
print(out)

abc
a1b1c1

In [80]:
a = input()
b = [1,1,1]

aaa

In [79]:
len(a)

3

In [81]:
len(b)

3